### ISSUE TITLE
Not able to see all users after running query in Postman

### ISSUE THREAD

**Issue by aelmoun2** [TableauExamples/Tableau_Postman#2]
Hi, I followed the steps as shown in the documentation. Everything came up good with no errors. However, when I run Get the user in site or a group I only get few of them not all of them. I was expected to get 950 users in the list, but instead I only got about 10% of that.
Any idea what might have caused that ?

Thank you

**Comment by tagyoureit** [comment]
Could be a few reasons...

1. The API only returns the first 100 users unless requested otherwise (https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Get_Users_on_Site -- see specifically `page size`).

2.  Are users in the same site?  You will need to get users specifically from each site.

3.  Not all users are in the group that you are requesting.

Try these and let me know if you solve it.

**Comment by aelmoun2** [comment]
Hi, 
I think it could be the first reason. I did run it again using the following:
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=6
I put pageNumber=6 because I have 5212 users in this site. It did run successfully, but I only got 200 users in the first page instead of 1000. Also how am I suppose to see the content of the other pages please?
Is there any way to move the results to an excel sheet?
Thank you lot

**Comment by tagyoureit** [comment]
I would expect page 0 to return results 1-1000; page 2 =1001-2000; page 6=5000-5212.  So it sounds like the API returned exactly what you asked it for.

You should try `?pageSize=6000` and it should give you all the users back.  If you include the `pageNumber` parameter you'll need to loop through the pages.

In order to get these users into XLS you would need to download and convert XML->XLS.  

If you would like an alternate method, see this KB article: http://kb.tableau.com/articles/howto/exporting-user-list

**Comment by aelmoun2** [comment]
Thank you for your response.
after running https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=6
I got the first page with only 218 lines. How can I loop through the pages please?
Also, please show me how to download as I can't find that option in my page.

Thank you

**Comment by tagyoureit** [comment]
To loop through them, you'll need to script this in Python/Java, or just run the commands sequentially:
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=1
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=2
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=3
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=4
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=5
https://Server_name/api/2.4/sites/69e71580-1129-4e9a-9bb3-b5b694453c79/users?pageSize=1000&pageNumber=6

You should just be able to copy/paste the XML results from postman into any text editor and then find some way to convert this to XLS or open it with an app (e.g. https://support.office.com/en-us/article/Import-XML-data-6eca3906-d6c9-4f0d-b911-c736da817fa4#bmopen_an_xml_data_file)
